---
title: "2D_simulation_LoD_classification"
author: "Helder Carneiro"
date: "2025-04-02"
output: html_document
---

This document contains the code for the simulation files and algorithm implementation of the limit of classification.

```{r packages , warning=F, message=FALSE}
windowsFonts(A = windowsFont("DejaVu Sans")) 
palette("Tableau10")

library(caret) #classification using train()
#library(kernlab)    
library(MASS) #generate the samples and calculate the augmented noise
library(dplyr) #data handling 
library(knitr) #knit options for the Rmarkdown report
library(kableExtra) #table options
library(pals)
library(plot3D)
library(rgl)
```

```{r functions, cache=TRUE }
source("predict_with_uncertainty_parallel_v4.R")
source("classify_sample_with_limits.R")
source("plot_functions.R")
```

```{r}
df_norm <- read.csv("glass_data.csv",check.names = F)
df_norm <- df_norm[,-c(3)]
wvl <- as.numeric(colnames(df_norm[,-c(1:2)]))
```

```{r}
palette(cols25()[c(6,5,7)])
set.seed(4)
sample_index <- unique(df_norm$Class)
sample <- sample(sample_index, length(sample_index)*1)

df_train <- df_norm[,]

```



```{r fig.width= 6.5, fig.height=4, fig.align="center", dpi =900, echo = F, warning=F}

palette(cols25()[c(6,5,7)])
layout_matrix <- matrix(c(1,1,1,2,2,2,
                          3,3,4,4,5,5),
                        nrow = 2,
                        
                        byrow = T)

layout(layout_matrix)

op <- par(family = "A")
par(mgp = c(1.5, 0.5, 0)) 
par(mar = c(3,3,1,1))

plot(wvl,
     log(class_BLK_mean),
     type = 'l',
     xlab = "eV",
     ylab = "Log Intensity",
     ylim = c(-10.5,0))
polygon(
  c(wvl, rev(wvl)),
  c(log(class_BLK_mean + class_BLK_sd), rev(log(class_BLK_mean - class_BLK_sd))),
  col = scales::alpha(palette()[1],0.4),
  border = NA
)
lines(wvl, log(class_BLK_mean), col = 1)  

polygon(
  c(wvl, rev(wvl)),
  c(log(class_ORA_mean + class_ORA_sd), rev(log(class_ORA_mean - class_ORA_sd))),
  col = scales::alpha(palette()[2],0.5),
  border = NA
)
lines(wvl, log(class_ORA_mean), col = 2) 

     legend("topright",
           legend = c("Orange", "Black"),
           lwd = 2,
           col = 2:1,
           inset = 0.01,
           box.lwd = 0.5)

plot(wvl,
     log(class_YEL_mean),
     type = 'l',
     xlab = "eV",
     ylab = "Log Intensity",
     ylim = c(-10.5,0))
polygon(
  c(wvl, rev(wvl)),
  c(log(class_YEL_mean + class_YEL_sd), rev(log(class_YEL_mean - class_YEL_sd))),
  col = scales::alpha(palette()[3],0.4),
  border = NA
)
lines(wvl, log(class_YEL_mean), col =3)  

polygon(
  c(wvl, rev(wvl)),
  c(log(class_ORA_mean + class_ORA_sd), rev(log(class_ORA_mean - class_ORA_sd))),
  col = scales::alpha(palette()[2],0.5),
  border = NA
)
lines(wvl, log(class_ORA_mean), col = 2) 

     legend("topright",
           legend = c("Orange", "Yellow"),
           lwd = 2,
           col = 2:3,
           inset = 0.01,
           box.lwd = 0.5)

     
smoothScatter(log(class_ORA_var),
     log(class_ORA_mean),
     colramp = colorRampPalette(c(NA, "cyan", "green", "yellow", "red")),
     xlab = "Log variance",
     ylab = "Log Intensity")

smoothScatter(log(class_BLK_var),
     log(class_BLK_mean),
     colramp = colorRampPalette(c(NA, "cyan", "green", "yellow", "red")),
     xlab = "Log variance",
     ylab = "Log Intensity")

smoothScatter(log(class_YEL_var),
     log(class_YEL_mean),
     colramp = colorRampPalette(c(NA, "cyan", "green", "yellow", "red")),
     xlab = "Log variance",
     ylab = "Log Intensity")
```


```{r fig.width=7, fig.height=7, fig.align="center", dpi =600, echo = F, warning=F}
png("YEL_cov_mesh2.png",
    width = 6,
    height = 6,
    units = "in",
    res = 600)

n_col <- 1000
jet.colors <- colorRampPalette(c( rep("blue", 25),  rep("cyan", 25), rep("green", 1), rep("yellow", 25), rep("red", 25)))


# Subset covariance matrix
cov_mat <- cov(class_YEL[,-c(1:2)])
step_size <- 10
cov_mat_small <- cov_mat[seq(1, nrow(cov_mat), by = step_size),
                         seq(1, ncol(cov_mat), by = step_size)]
x_small <- wvl[seq(1, nrow(cov_mat), by = step_size)]
y_small <- x_small

# Set symmetric color limits
zlim <- max(abs(cov_mat_small))
col_breaks <- seq(-zlim, zlim, length.out = n_col + 1)

# Plot with forced green center
persp3D(x = x_small, y = y_small, z = cov_mat_small,
        colvar = cov_mat_small,
        col = jet.colors(n_col),
        colkey = FALSE,     
        clab = NULL,
        clim = c(-zlim, zlim),
        cex.axis = 0.7,
        lwd = 0.000001, alpha = 0.8,
        border = "black",
        theta = 325, phi = 15, expand = 1,
        ticktype = "detailed",
        xlab = "eV", ylab = "eV", zlab = "")
```






```{r}
df_train <- df_norm
df_train <- df_train[df_train$Class!="YEL", ]

df_train$Class <- ifelse(df_train$Class=="ORA",1,2)
df_train <- df_train[order(df_train$Class),]
df_train$Sample <- rep(1:10, each = 5)


center_parameters <- preProcess(df_train[,-c(1:2)], method = "center")
df_center <- predict(center_parameters, df_train[,-c(1:2)])
df_center <- data.frame(cbind(df_train[,c(1:2)],df_center ), check.names = F)


df_center_mean <- aggregate(. ~ Class + Sample, data = df_center, FUN = mean)

```


```{r}

pls_1 <- train(y = as.factor(df_center_mean$Class),
                   x = df_center_mean[,-c(1:2)], 
                   method = "pls",
                  tuneGrid = expand.grid(ncomp = c(2)))
```


```{r}
 
loc_pred <- predict_with_uncertainty_parallel(df_center[,-c(1)],
                                              pls_1,
                                              n_sim = 500,
                                              return_simulations = T)

```


```{r uncertainty results, cache = TRUE, echo = F}

loc_pred_results <- Reduce(rbind, lapply(loc_pred, function(x) {
  Reduce(cbind, x[names(x) != "sim_X"])
}))

colnames(loc_pred_results) <- names(loc_pred[[1]])[-7]


loc_pred_results <- data.frame(class = df_center_mean$Class, loc_pred_results)
loc_pred_results$sample <- rep(1:5, 2)

loc_pred_results$y_mean <- round(as.numeric(loc_pred_results$y_mean), digits = 4)
loc_pred_results$y_sd <- round(as.numeric(loc_pred_results$y_sd), digits = 4)
loc_pred_results$area_above_0 <- round(as.numeric(loc_pred_results$area_above_0), digits = 3)
loc_pred_results$area_below_0 <- round(as.numeric(loc_pred_results$area_below_0), digits = 3)

kable(loc_pred_results,
      format = 'html',
      caption = "Table 1. Results of the predict_with_uncertainty_parallel() function. ") %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
```




```{r}
palette(cols25()[c(5,6)])
class_index <- rep(1:2, each = 5)
  replicate_index <- df_center$Sample
  

  explained_variance <- (pls_1$finalModel$Xvar / pls_1$finalModel$Xtotvar)*100
  
  mean_scores <- as.matrix(df_center_mean[,-c(1:2)]) %*% pls_1$finalModel$projection
  rep_scores <- as.matrix(df_center[,-c(1:2)]) %*% pls_1$finalModel$projection
  
  MC_noise_all <-  Reduce(rbind, lapply(loc_pred, function(x) {
                                                  Reduce(cbind, x[names(x) == "sim_X"])}))

  noise_scores <- as.matrix(MC_noise_all) %*% pls_1$finalModel$projection
  
  mean_colors <- palette()[rep(1:2, each = 5)]
  rep_colors <- palette()[rep(1:2, each = 25)]
  noise_colors <- palette()[rep(1:2, each = 5*500)]
  n_samples <- 5
```


```{r fig.width= 7.5, fig.height=2.5, fig.align="center", dpi =600, echo = F}


layout_matrix <- matrix(1:3,
                        nrow = 1,
                        byrow = F)

layout(layout_matrix)

op <- par(family = "A")
par(mgp = c(1.5, 0.5, 0)) 
par(mar = c(3,3,1,1))


  axis_lim <- max(abs(mean_scores[,1]))*1.5
  plot(mean_scores[,1],
       mean_scores[,2],
       type = 'n',
       xlim = c(-axis_lim,axis_lim),
       ylim = c(-axis_lim,axis_lim),
       xlab = paste0("LV 1 - ", round(explained_variance[1], digits = 2),"%"),
       ylab = paste0("LV 2 - ", round(explained_variance[2], digits = 2),"%"),
       cex.axis = 0.8,
       col.axis="gray30",
       cex.lab = 1)
  abline(v = 0, h = 0, col = "gray95")
  
  
  segments(x0=rep_scores[,1],
             y0=rep_scores[,2],
             x1=rep(mean_scores[,1], each = 5),
             y1=rep(mean_scores[,2], each = 5),
             col = scales::alpha(rep_colors, 0.3),
             lwd = 1)
  
  points(rep_scores[,1],
         rep_scores[,2],
         pch = 16,
         cex = 0.5,
         col = scales::alpha(rep_colors, 0.5))
  
  points(mean_scores[,1],
         mean_scores[,2],
          pch = 24,
         cex = 1.5,
         col = "gray10",
         bg = scales::alpha(mean_colors, 1))
  
   legend("topright",
           legend = c("Orange", "Black"),
           pch = 24,
           cex = 1,
           inset = 0.01,
           box.lwd = 0.5,
           pt.bg = c(1:2))
   
mtext("a", side = 3, line = -1.8, adj = 0.04, font = 1, cex = 1.5)  

  plot(mean_scores[,1],
       mean_scores[,2],
       type = 'n',
       xlim = c(-axis_lim,axis_lim),
       ylim = c(-axis_lim,axis_lim),
       xlab = paste0("LV 1 - ", round(explained_variance[1], digits = 2),"%"),
       ylab = paste0("LV 2 - ", round(explained_variance[2], digits = 2),"%"),
       cex.axis = 0.8,
       col.axis="gray30",
       cex.lab = 1)
  abline(v = 0, h = 0, col = "gray95")
  
  
  segments(x0=noise_scores[,1],
             y0=noise_scores[,2],
             x1=rep(mean_scores[,1], each = 500),
             y1=rep(mean_scores[,2], each = 500),
             col = scales::alpha(noise_colors, 0.3),
             lwd = 1)
  
  points(noise_scores[,1],
         noise_scores[,2],
         pch = 16,
         cex = 0.5,
         col = scales::alpha(noise_colors, 0.5))
  
  points(mean_scores[,1],
         mean_scores[,2],
          pch = 24,
         cex = 1.5,
         col = "gray10",
         bg = scales::alpha(mean_colors, 1))

mtext("b", side = 3, line = -1.8, adj = 0.04, font = 1, cex = 1.5)



plot(1:n_samples,
       c(1:n_samples),
       type = "n",
       xlab = expression(italic(hat(y)), family = "Helvetica-Oblique"),
       ylab = "Samples",
       ylim= c(1,max(n_samples)*1.2),
       xlim = c(-1,1),
      # yaxt = c(1:max(n_samples_class)),
       cex.axis = 0.8,
       col.axis="gray30",
       cex.lab = 1
  )

  abline(v = 0, col = "black", lty = 2)

    up_lim <- loc_pred_results$y_mean + 2*loc_pred_results$y_sd
    bot_lim <- loc_pred_results$y_mean - 2*loc_pred_results$y_sd


    arrows(x0 = bot_lim,
           x1 = up_lim,
           y0 = rep(1:5, 2),
           y1 = rep(1:5, 2),
           col = scales::alpha(mean_colors, 0.6),
           code = 3,
           angle = 90,
           length = 0.05)

    points(loc_pred_results$y_mean,
           rep(1:5, 2),
           pch = 24,
           cex = 1.5,
           col = "gray10",
           bg = mean_colors)
mtext("c", side = 3, line = -1.8, adj = 0.04, font = 1, cex = 1.5)
```



```{r}
df_train <- df_norm
df_train <- df_train[df_train$Class!="DPW", ]

df_train$Class <- ifelse(df_train$Class=="ORA",1,2)
df_train <- df_train[order(df_train$Class),]
df_train$Sample <- rep(1:10, each = 5)


center_parameters <- preProcess(df_train[,-c(1:2)], method = "center")
df_center <- predict(center_parameters, df_train[,-c(1:2)])
df_center <- data.frame(cbind(df_train[,c(1:2)],df_center ), check.names = F)


df_center_mean <- aggregate(. ~ Class + Sample, data = df_center, FUN = mean)

```



```{r}
pls_2 <- train(y = as.factor(df_center_mean$Class),
                   x = df_center_mean[,-c(1:2)], 
                   method = "pls")
```


```{r}
system.time({
loc_pred_2 <- predict_with_uncertainty_parallel(df_center[,-c(1)],
                                              pls_2,
                                              n_sim = 500,
                                              return_simulations = T)
})
```


```{r uncertainty results, cache = TRUE, echo = F}

loc_pred_results_2 <- Reduce(rbind, lapply(loc_pred_2, function(x) {
  Reduce(cbind, x[names(x) != "sim_X"])
}))

colnames(loc_pred_results_2) <- names(loc_pred_2[[1]])[-7]


loc_pred_results_2 <- data.frame(class = df_center_mean$Class, loc_pred_results_2)
loc_pred_results_2$sample <- rep(1:5, 2)

loc_pred_results_2$y_mean <- round(as.numeric(loc_pred_results_2$y_mean), digits = 4)
loc_pred_results_2$y_sd <- round(as.numeric(loc_pred_results_2$y_sd), digits = 4)
loc_pred_results_2$area_above_0 <- round(as.numeric(loc_pred_results_2$area_above_0), digits = 3)
loc_pred_results_2$area_below_0 <- round(as.numeric(loc_pred_results_2$area_below_0), digits = 3)

kable(loc_pred_results_2,
      format = 'html',
      caption = "Table 1. Results of the predict_with_uncertainty_parallel() function. ") %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
```


```{r}
palette(cols25()[c(5,7)])
class_index <- rep(1:2, each = 5)
  replicate_index <- df_center$Sample
  

  explained_variance <- (pls_2$finalModel$Xvar / pls_2$finalModel$Xtotvar)*100
  
  mean_scores <- as.matrix(df_center_mean[,-c(1:2)]) %*% pls_2$finalModel$projection
  rep_scores <- as.matrix(df_center[,-c(1:2)]) %*% pls_2$finalModel$projection
  
  MC_noise_all <-  Reduce(rbind, lapply(loc_pred_2, function(x) {
                                                  Reduce(cbind, x[names(x) == "sim_X"])}))

  noise_scores <- as.matrix(MC_noise_all[,]) %*% pls_2$finalModel$projection
  
  
  mean_colors <- palette()[rep(1:2, each = 5)]
  rep_colors <- palette()[rep(1:2, each = 25)]
  noise_colors <- palette()[rep(1:2, each = 5*500)]
  n_samples <- 5
```

```{r fig.width= 7.5, fig.height=2.5, fig.align="center", dpi =300, echo = F}


layout_matrix <- matrix(1:3,
                        nrow = 1,
                        byrow = F)

layout(layout_matrix)

op <- par(family = "A")
par(mgp = c(1.5, 0.5, 0)) 
par(mar = c(3,3,1,1))


  axis_lim <- max(abs(mean_scores[,1]))*1.5
  plot(mean_scores[,1],
       mean_scores[,2],
       type = 'n',
       xlim = c(-axis_lim,axis_lim),
       ylim = c(-axis_lim,axis_lim),
       xlab = paste0("PC 1 - ", round(explained_variance[1], digits = 2),"%"),
       ylab = paste0("PC 2 - ", round(explained_variance[2], digits = 2),"%"),
       cex.axis = 0.8,
       col.axis="gray30",
       cex.lab = 1)
  abline(v = 0, h = 0, col = "gray95")
  
  
  segments(x0=rep_scores[,1],
             y0=rep_scores[,2],
             x1=rep(mean_scores[,1], each = 5),
             y1=rep(mean_scores[,2], each = 5),
             col = scales::alpha(rep_colors, 0.3),
             lwd = 1)
  
  points(rep_scores[,1],
         rep_scores[,2],
         pch = 16,
         cex = 0.5,
         col = scales::alpha(rep_colors, 0.5))
  
  points(mean_scores[,1],
         mean_scores[,2],
          pch = 24,
         cex = 1.5,
         col = "gray10",
         bg = scales::alpha(mean_colors, 1))
     legend("topright",
           legend = c("Orange", "Yellow"),
           pch = 24,
           cex = 1,
           inset = 0.01,
           box.lwd = 0.5,
           pt.bg = c(1:2))
mtext("a", side = 3, line = -1.8, adj = 0.04, font = 1, cex = 1.5)  

  plot(mean_scores[,1],
       mean_scores[,2],
       type = 'n',
       xlim = c(-axis_lim,axis_lim),
       ylim = c(-axis_lim,axis_lim),
       xlab = paste0("LV 1 - ", round(explained_variance[1], digits = 2),"%"),
       ylab = paste0("LV 2 - ", round(explained_variance[2], digits = 2),"%"),
       cex.axis = 0.8,
       col.axis="gray30",
       cex.lab = 1)
  abline(v = 0, h = 0, col = "gray95")
  
  
  segments(x0=noise_scores[,1],
             y0=noise_scores[,2],
             x1=rep(mean_scores[,1], each = 500),
             y1=rep(mean_scores[,2], each = 500),
             col = scales::alpha(noise_colors, 0.3),
             lwd = 1)
  
  points(noise_scores[,1],
         noise_scores[,2],
         pch = 16,
         cex = 0.5,
         col = scales::alpha(noise_colors, 0.5))
  
  points(mean_scores[,1],
         mean_scores[,2],
          pch = 24,
         cex = 1.5,
         col = "gray10",
         bg = scales::alpha(mean_colors, 1))

mtext("b", side = 3, line = -1.8, adj = 0.04, font = 1, cex = 1.5)



plot(1:n_samples,
       c(1:n_samples),
       type = "n",
       xlab = expression(italic(hat(y)), family = "Helvetica-Oblique"),
       ylab = "Samples",
       ylim= c(1,max(n_samples)*1.2),
       xlim = c(-1,1),
      # yaxt = c(1:max(n_samples_class)),
       cex.axis = 0.8,
       col.axis="gray30",
       cex.lab = 1
  )

  abline(v = 0, col = "black", lty = 2)

    up_lim <- loc_pred_results_2$y_mean + 2*loc_pred_results_2$y_sd
    bot_lim <- loc_pred_results_2$y_mean - 2*loc_pred_results_2$y_sd


    arrows(x0 = bot_lim,
           x1 = up_lim,
           y0 = rep(1:5, 2),
           y1 = rep(1:5, 2),
           col = scales::alpha(mean_colors, 0.6),
           code = 3,
           angle = 90,
           length = 0.05)

    points(loc_pred_results_2$y_mean,
           rep(1:5, 2),
           pch = 24,
           cex = 1.5,
           col = "gray10",
           bg = mean_colors)
mtext("c", side = 3, line = -1.8, adj = 0.04, font = 1, cex = 1.5)
```





```{r}
df_train <- df_norm


df_train$Class <- ifelse(df_train$Class=="ORA",1,2)
df_train <- df_train[order(df_train$Class),]
df_train$Sample <- rep(1:15, each = 5)


center_parameters <- preProcess(df_train[,-c(1:2)], method = "center")
df_center <- predict(center_parameters, df_train[,-c(1:2)])
df_center <- data.frame(cbind(df_train[,c(1:2)],df_center ), check.names = F)


df_center_mean <- aggregate(. ~ Class + Sample, data = df_center, FUN = mean)

```


```{r}
pls_3 <- train(y = as.factor(df_center_mean$Class),
                   x = df_center_mean[,-c(1:2)], 
                   method = "pls")
```


```{r}
system.time({
loc_pred_3 <- predict_with_uncertainty_parallel(df_center[,-c(1)],
                                              pls_3,
                                              n_sim = 500,
                                              return_simulations = T)
})
```


```{r uncertainty results, cache = TRUE, echo = F}

loc_pred_results_3 <- Reduce(rbind, lapply(loc_pred_3, function(x) {
  Reduce(cbind, x[names(x) != "sim_X"])
}))

colnames(loc_pred_results_3) <- names(loc_pred_3[[1]])[-7]


loc_pred_results_3 <- data.frame(class = df_center_mean$Class, loc_pred_results_3)
loc_pred_results_3$sample <- rep(1:5, 3)

loc_pred_results_3$y_mean <- round(as.numeric(loc_pred_results_3$y_mean), digits = 4)
loc_pred_results_3$y_sd <- round(as.numeric(loc_pred_results_3$y_sd), digits = 4)
loc_pred_results_3$area_above_0 <- round(as.numeric(loc_pred_results_3$area_above_0), digits = 3)
loc_pred_results_3$area_below_0 <- round(as.numeric(loc_pred_results_3$area_below_0), digits = 3)

kable(loc_pred_results_3,
      format = 'html',
      caption = "Table 1. Results of the predict_with_uncertainty_parallel() function. ") %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
```

```{r}
palette(cols25()[c(5,6,7)])
class_index <- rep(1:3, each = 5)
  replicate_index <- df_center$Sample
  

  explained_variance <- (pls_3$finalModel$Xvar / pls_3$finalModel$Xtotvar)*100
  
  mean_scores <- as.matrix(df_center_mean[,-c(1:2)]) %*% pls_3$finalModel$projection
  rep_scores <- as.matrix(df_center[,-c(1:2)]) %*% pls_3$finalModel$projection
  
  MC_noise_all <-  Reduce(rbind, lapply(loc_pred_3, function(x) {
                                                  Reduce(cbind, x[names(x) == "sim_X"])}))

  noise_scores <- as.matrix(MC_noise_all[,]) %*% pls_3$finalModel$projection
  
  
  mean_colors <- palette()[rep(1:3, each = 5)]
  rep_colors <- palette()[rep(1:3, each = 25)]
  noise_colors <- palette()[rep(1:3, each = 5*500)]
  n_samples <- 5
```



```{r fig.width= 7.5, fig.height=2.5, fig.align="center", dpi =300, echo = F}


layout_matrix <- matrix(1:3,
                        nrow = 1,
                        byrow = F)

layout(layout_matrix)

op <- par(family = "A")
par(mgp = c(1.5, 0.5, 0)) 
par(mar = c(3,3,1,1))


  axis_lim <- max(abs(mean_scores[,2]))*1.5
  plot(mean_scores[,2],
       mean_scores[,3],
       type = 'n',
       xlim = c(-axis_lim,axis_lim),
       ylim = c(-axis_lim,axis_lim),
       xlab = paste0("LV 2 - ", round(explained_variance[2], digits = 2),"%"),
       ylab = paste0("LV 3 - ", round(explained_variance[3], digits = 2),"%"),
       cex.axis = 0.8,
       col.axis="gray30",
       cex.lab = 1)
  abline(v = 0, h = 0, col = "gray95")
  
  
  segments(x0=rep_scores[,2],
             y0=rep_scores[,3],
             x1=rep(mean_scores[,2], each = 5),
             y1=rep(mean_scores[,3], each = 5),
             col = scales::alpha(rep_colors, 0.3),
             lwd = 1)
  
  points(rep_scores[,2],
         rep_scores[,3],
         pch = 16,
         cex = 0.5,
         col = scales::alpha(rep_colors, 0.5))
  
  points(mean_scores[,2],
         mean_scores[,3],
          pch = 24,
         cex = 1.5,
         col = "gray10",
         bg = scales::alpha(mean_colors, 1))
       legend("topright",
           legend = c("Orange", "Black","Yellow"),
           pch = 24,
           cex = 1,
           inset = 0.01,
           box.lwd = 0.5,
           pt.bg = c(1:3))
       
mtext("a", side = 3, line = -1.8, adj = 0.04, font = 1, cex = 1.5)  

  plot(mean_scores[,2],
       mean_scores[,3],
       type = 'n',
       xlim = c(-axis_lim,axis_lim),
       ylim = c(-axis_lim,axis_lim),
       xlab = paste0("LV 2 - ", round(explained_variance[2], digits = 2),"%"),
       ylab = paste0("LV 3 - ", round(explained_variance[3], digits = 2),"%"),
       cex.axis = 0.8,
       col.axis="gray30",
       cex.lab = 1)
  abline(v = 0, h = 0, col = "gray95")
  
  
  segments(x0=noise_scores[,2],
             y0=noise_scores[,3],
             x1=rep(mean_scores[,2], each = 500),
             y1=rep(mean_scores[,3], each = 500),
             col = scales::alpha(noise_colors, 0.3),
             lwd = 1)
  
  points(noise_scores[,2],
         noise_scores[,3],
         pch = 16,
         cex = 0.5,
         col = scales::alpha(noise_colors, 0.5))
  
  points(mean_scores[,2],
         mean_scores[,3],
          pch = 24,
         cex = 1.5,
         col = "gray10",
         bg = scales::alpha(mean_colors, 1))

mtext("b", side = 3, line = -1.8, adj = 0.04, font = 1, cex = 1.5)



plot(1:n_samples,
       c(1:n_samples),
       type = "n",
       xlab = expression(italic(hat(y)), family = "Helvetica-Oblique"),
       ylab = "Samples",
       ylim= c(1,max(n_samples)*1.2),
       xlim = c(-1,1),
      # yaxt = c(1:max(n_samples_class)),
       cex.axis = 0.8,
       col.axis="gray30",
       cex.lab = 1
  )

  abline(v = 0, col = "black", lty = 2)

    up_lim <- loc_pred_results_3$y_mean + 2*loc_pred_results_3$y_sd
    bot_lim <- loc_pred_results_3$y_mean - 2*loc_pred_results_3$y_sd


    arrows(x0 = bot_lim,
           x1 = up_lim,
           y0 = rep(1:5, 3),
           y1 = rep(1:5, 3),
           col = scales::alpha(mean_colors, 0.6),
           code = 3,
           angle = 90,
           length = 0.05)

    points(loc_pred_results_3$y_mean,
           rep(1:5, 3),
           pch = 24,
           cex = 1.5,
           col = "gray10",
           bg = mean_colors)
mtext("c", side = 3, line = -1.8, adj = 0.04, font = 1, cex = 1.5)
```


